name: 'Setup Python Environment'
description: 'Set up Python and restore cached environment'

inputs:
  python-version:
    description: 'Python version to set up'
    required: true
  cache-key:
    description: 'Cache key for Python environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python [${{ inputs.python-version }}]
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore Python environment
      uses: actions/cache/restore@v5
      with:
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}
        key: ${{ inputs.cache-key }}
        fail-on-cache-miss: true

    - name: Display installed Python modules
      shell: bash
      run: |
        pip list