import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from NuRadioReco.utilities import units
from plotly import subplots
import numpy as np
import plotly.graph_objs as go
import json
import sys
import base64
from io import StringIO

from NuRadioReco.detector.detector_mongo import det
#from NuRadioReco.detector.webinterface.utils.sparameter_helper import validate_Sdata,  enable_board_name_input, plot_Sparameters, sparameters_layout
from NuRadioReco.detector.webinterface.utils.Vpol_helper import validate_Sdata, plot_Sparameters, sparameters_layout
from NuRadioReco.detector.webinterface.utils.table import get_table
from NuRadioReco.detector.webinterface.utils.units import str_to_unit
from NuRadioReco.detector.webinterface.app import app


table_name = "Vpol"
component_name = "exactvpol"
full_tables = "full_tables"
layout = html.Div([
    html.H3('Build a Station', id='trigger'),
    dcc.Link('Go back to menu', href='/apps/menu'),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Station Name:", style={'float':'left'}),
        dcc.Dropdown(
            id='station_list',
            options=[
              {'label': '11 (Nanoq)', 'value': 11},
              {'label': '21 (Amaroq)', 'value': 21},
              {'label': '22 (Avinngaq)', 'value': 22},
              ],
            placeholder='Pick your station',
            style={'width': '200px', 'float':'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 0 (PA VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list0',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list0',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list0',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi0",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta0",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x0",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y0",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z0",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi0",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta0",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time0",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time0",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 1 (PA VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list1',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list1',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list1',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi1",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta1",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x1",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y1",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z1",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi1",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta1",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time1",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time1",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 2 (PA VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list2',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list2',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list2',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi2",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta2",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x2",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y2",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z2",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi2",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta2",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time2",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time2",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 3 (PA VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list3',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list3',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list3',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi3",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta3",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x3",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y3",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z3",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi3",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta3",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time3",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time3",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 4 (Pwr String HPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Hpol_list4',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your HPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list4',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list4',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi4",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta4",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x4",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y4",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z4",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi4",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta4",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time4",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time4",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 5 (Pwr String VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list5',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list5',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list5',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi5",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta5",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x5",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y5",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z5",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi5",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta5",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time5",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time5",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 6 (Pwr String VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list6',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list6',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list6',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi6",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta6",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x6",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y6",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z6",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi6",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta6",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time6",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time6",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 7 (Pwr String VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list7',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list7',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list7',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi7",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta7",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x7",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y7",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z7",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi7",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta7",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time7",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time7",
                  type="number",
                  placeholder="decomission_time00",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 8 (Pwr String HPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Hpol_list8',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your HPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list8',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list8',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi8",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta8",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x8",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y8",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z8",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi8",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta8",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time8",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time8",
                  type="number",
                  placeholder="decomission_time00",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 9 (Hlpr String B VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list9',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list9',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list9',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi9",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta9",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x9",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y9",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z9",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi9",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta9",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time9",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time9",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 10 (Hlpr String B VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Vpol_list10',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list10',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list10',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi10",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta10",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x10",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y10",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z10",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi10",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta10",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time10",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time10",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 11 (Hlpr String B HPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='Hpol_list11',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your HPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list11',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list11',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your downhole Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi11",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta11",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x11",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y11",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z11",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi11",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta11",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time11",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time11",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 12 (Surface Helper C):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list12',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list12',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list12',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi12",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta12",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x12",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y12",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z12",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi12",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta12",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time12",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time12",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 13 (Surface Helper C):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list13',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list13',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list13',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi13",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta13",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x13",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y13",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z13",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi13",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta13",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time13",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time13",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 14 (Surface Helper C):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list14',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list14',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list14',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi14",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta14",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x14",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y14",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z14",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi14",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta14",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time14",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time14",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 15 (Surface Power):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list15',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list15',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list15',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi15",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta15",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x15",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y15",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z15",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi15",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta15",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time15",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time15",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 16 (Surface Power):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list16',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list16',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list16',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi16",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta16",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x16",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y16",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z16",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi16",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta16",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time16",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time16",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 17 (Surface Power):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list17',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list17',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list17',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi17",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta17",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x17",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y17",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z17",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi17",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta17",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time17",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time17",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 18 (Surface Helper B):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list18',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list18',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list18',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi18",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta18",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x18",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y18",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z18",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi18",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta18",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time18",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time18",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 19 (Surface Helper B):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list19',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list19',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list19',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi19",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta19",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x19",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y19",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z19",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi19",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta19",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time19",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time19",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 20 (Surface Helper B):", style={'float':'left'}),
        dcc.Dropdown(
            id='LPDA_list20',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your LPDA',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='Surface_list20',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Board',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list20',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your SURFACE Cable',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi20",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta20",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x20",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y20",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z20",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi20",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta20",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time20",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time20",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 21 (Helper C VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='VPol_list21',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list21',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list21',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi21",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta21",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x21",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y21",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z21",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi21",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta21",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time21",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time21",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 22 (Helper C VPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='VPol_list22',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your VPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list22',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list22',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi22",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta22",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x22",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y22",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z22",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi22",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta22",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time22",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time22",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([html.Div("Channel 23 (Helper C HPol):", style={'float':'left'}),
        dcc.Dropdown(
            id='HPol_list21',
            options=[
                {'label': '', 'value': "CABLE"},
                ],
            placeholder='Pick your HPol',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='IGLU_list23',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your IGLU',
            style={'width': '200px', 'float':'left'}),
        dcc.Dropdown(
            id='CABLE_list23',
            options=[
                {'label': 'A54321', 'value': "CABLE"},
                ],
            placeholder='Pick your Fiber',
            style={'width': '200px', 'float':'left'}),
        dcc.Input(id="orientation_phi23",
                  type="number",
                  placeholder="orientation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="orientation_theta23",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_x23",
                  type="number",
                  placeholder="positiion_x",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_y23",
                  type="number",
                  placeholder="position_y",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="position_z23",
                  type="number",
                  placeholder="position_z",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_phi23",
                  type="number",
                  placeholder="rotation_phi",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="rotation_theta23",
                  type="number",
                  placeholder="orientation_theta",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="comission_time23",
                  type="number",
                  placeholder="comission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        dcc.Input(id="decomission_time23",
                  type="number",
                  placeholder="decomission_time",
                  style={'width': '200px',
                         'float': 'left'}),
        ]),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Div([
        html.Button('Insert New Station Configuration', id=table_name + component_name, disabled=True),
    ], style={'width': "100%", "overflow": "hidden"}),



    ])



def update_dropdown_VPol_names(n_intervals, options, table_name):
    """
    updates the dropdown menu with existing antenna names from the database
    """
    if(get_table(table_name) is not None):
        for VPol_name in get_table(table_name).distinct("name"):
            options.append(
                {"label": VPol_name, "value": VPol_name}
            )
        return options
