name: Check compatibility

on:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  version:
    strategy:
      fail-fast: false # continue even if one of the versions fails
      matrix:
        python_version: ["3.9", "3.11", "3.x"] # 3.x = latest available
        os: [ubuntu-latest]
        include:
          - python_version: "3.7"
            os: ubuntu-22.04
          - python_version: "3.8" # technically available on 24.04 but not pre-installed
            os: ubuntu-22.04
    uses: ./.github/workflows/run_tests.yaml
    with:
      python_version: ${{ matrix.python_version }}
      os: ${{ matrix.os }}
